module.exports = {
  message: (module, action, status = true) => {
    return `${module} ${action} ${status ? 'Successfully' : 'Failed'}`;
  },
  notFound: (module) => {
    return `${module} Not Found`;
  },
  alreadyExist: (module) => {
    return `${module} Already Exist`;
  },
  cantBeEmpty: (fieldName) => {
    return `${fieldName} can not be empty`;
  },
  invalid: (fieldName) => {
    return `${fieldName} is invalid`;
  },
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_STATUS: 500,
  userModule: 'User',
  authModule: 'Auth',
  projectModule: 'Project',
  taskModule: 'Task',
  uploadModule: 'Upload',
  organizationModule: 'Organization',
  organizationUserModule: 'Organization User',
  SEND_AUTH_TOKEN: 'Please send the Authentication token',
  JWT_SECRET_KEY: 'jwt_secret_key',
  USER_NOT_EXIST_OR_ACCESS:
    'The user is either inaccessible or does not exist!',
  UNAUTHENTICATED: 'Access unauthorized!',
  INVALID_OR_EXPIRED_TOKEN: 'Invalid or expired token',
  USER_AUTH_FAILED: 'User authentication failed',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  LOGIN_SUCCESSFUL: 'Login successful!',
  USER_CREATION_FAILED: 'User creation from Facebook failed',
  SEARCH_SUCCESS: 'Search success',
  PATIENT_NOT_FOUND: 'Patient not found!',
  PATIENT_EXISTS: 'Patient already exists!',
  CREATE_SUCCESS: 'Patient created successfully',
  UPDATE_SUCCESS: 'Patient updated successfully',
  UPDATE_SAME_DATA_ERROR:
    'Cannot update with the same data. Please provide different data.',
  CANT_BE_EMPTY: 'Can not be empty ',
  INVALID_ALPHABETS: 'Should contain only alphabets',
  INVALID_GENDER: 'Invalid gender - Should be either "male" or "female"',
  INVALID_DATE_FORMAT:
    'Invalid date format - Enter a valid date in the format YYYY-MM-DD.',
  INVALID_EMAIL: 'Invalid email - Enter a valid email address',
  INVALID_PHONE_NUMBER:
    'Invalid phone number - Enter a valid USA phone number.',
  UPDATE_CONFLICT_ERROR:
    'Data conflict with another patient. Please check and update your data.',
  INVALID_PATTERN: 'Invalid pattern for',
  USER_NOT_SYSTEM_EXIST: 'The user is currently not registered in the system',
  USER_NOT_ACTIVE: 'The user is not active',
  EMAIL_ALREADY_EXIST_WITH_OTHER_USER: 'Email already exist with other user',
  PHONE_NUMBER_ALREADY_EXIST_WITH_OTHER_USER:
    'Phone number already exist with other user',
  EMAIL_ALREADY_EXIST_WITH_OTHER_ORGANIZATION:
    'Email already exist with other organization',
  PHONE_NUMBER_ALREADY_EXIST_WITH_OTHER_ORGANIZATION:
    'Phone number already exist with other organization',
  WONT_CREATE_ORGANIZATION_WITH_NAME_TOI:
    'You can not create organization with name TOI',
  WONT_UPDATE_ORGANIZATION_WITH_NAME_TOI:
    'You can not update organization with name TOI',
  NPI_DETAIL: 'Npi details',
  NO_NPI_FOUND: 'No record found associated with NPI number',
  NPI_NUMERIC_ERROR_MESSAGE: 'NPI Number must be numeric',
  NPI_LENGTH_ERROR: 'NPI must be 10 digits',
  CREATE_INSURANCE_SUCCESS: 'Insurance information successfully created',
  PATIENT_ID_REQUIRED: 'Patient ID is required',
  INSURANCE_ALREADY_EXISTS: 'Insurance is already exist.',
  MEDICARE_ID_REQUIRED: 'MedicareID is required',
  PRIMARY_SUBSCRIBER_NUMBER_REQUIRED: 'Primary Subscriber Number is required',
  PRIMARY_GROUP_NUMBER_REQUIRED: 'Primary Group Number is required',
  LOB_REQUIRED: 'LOB is required',
  PRIMARY_START_DATE_REQUIRED: 'Primary Start Date is required',
  PRIMARY_END_DATE_REQUIRED: 'Primary End Date is required',
  FILE_UPLOADED: 'File uploaded successfully',
  FILE_UPLOAD_ERROR: 'Error while uploading file',
  NPI_ALREADY_EXISTS: 'Npi with the provided Npi Number already exists.',
  MEDICAL_HISTORY_ID_REQUIRED: 'Medical History ID is required.',
  FIRST_NAME_REQUIRED: 'First Name is required.',
  LAST_NAME_REQUIRED: 'Last Name is required.',
  NPI_NUMBER_REQUIRED: 'NPI Number is required.',
  NPI_CREATED: 'Npi created successfully.',
  MIDDLE_NAME_REQUIRED: 'Middle name is required.',
  CREDENTIAL_REQUIRED: 'Credential is required.',
  SOLE_PROPRIETOR_REQUIRED: 'Sole proprietor is required.',
  GENDER_REQUIRED: 'Gender is required.',
  ENUMERATION_DATE_REQUIRED: 'Enumeration date is required.',
  ENUMERATION_DATE_INVALID: 'Enumeration date must be a valid date.',
  LAST_UPDATED_REQUIRED: 'Last updated date is required.',
  LAST_UPDATED_INVALID: 'Last updated date must be a valid date.',
  STATUS_REQUIRED: 'Status is required.',
  NAME_PREFIX_REQUIRED: 'Name prefix is required.',
  ORDER_ALREADY_EXISTS: 'Order with the same orderId already exists',
  ORDER_CREATED_SUCCESSFULLY: 'Order created successfully',
  PATIENT_ID_NUMERIC_ERROR: 'Patient ID must be a numeric value',
  ORDER_NOT_FOUND: 'Order not found',
  ORDER_RETRIEVED_SUCCESSFULLY: 'Order retrieved successfully',
  ORDERS_LISTED_SUCCESSFULLY: 'Orders listed successfully',
  INVALID_FILE_FORMAT:
    'Invalid file type. Only images (JPEG, PNG, GIF) and PDFs are allowed.',
  EXCEED_FILE_SIZE_LIMIT:
    'File size exceeds the maximum allowed limit of 10 MB.',
  NO_FILE_UPLOADED: 'No file uploaded',
  ORDER_UPDATED_SUCCESSFULLY: 'Order updated successfully',
  ORDER_SAVED_SUCCESSFULLY: 'Order saved as draft successfully.',
  CAPS_ASCENDING: 'ASC',
  CAPS_DESCENDING: 'DESC',
  UPDATED_AT: 'updatedAt',
  PATIENT_RETRIEVED_SUCCESSFULLY: 'Patient retrieved successfully',
  INSURANCE_RETRIEVED_SUCCESSFULLY: 'Insurance retrieved successfully',
  INSURANCE_NOT_FOUND: 'Insurance not found',
  MEDICAL_HISTORY_RETRIEVED_SUCCESSFULLY:
    'Medical history retrieved successfully',
  MEDICAL_HISTORY_NOT_FOUND: 'Medical history not found',
  MEDICAL_RECORD_NOT_FOUND: 'Medical Record not found',
  MEDICAL_RECORD_RETRIEVED_SUCCESSFULLY:
    'Medical Record retrieved successfully',
  LATEST_DOCUMENTS_FETCHED: 'Latest documents fetched successfully.',
  HISTORY_ID_REQUIRED: 'History ID is required',
  HISTORY_ID_NUMERIC_ERROR: 'History ID must be a numeric value',
  RECORD_ID_REQUIRED: 'Record ID is required',
  RECORD_ID_NUMERIC_ERROR: 'Record ID must be a numeric value',
  INSURANCE_ID_REQUIRED: 'Insurance ID is required',
  INSURANCE_ID_NUMERIC_ERROR: 'Insurance ID must be a numeric value',
  PATIENT_DOCUMENT_NOT_FOUND: 'Patient Document not found.',
  THRESHOLD: 1024,
  MUST_BE_NUMBER: 'Must be a number: ',
  DIAGNOSIS_IMPORTED: 'CSV data imported successfully',
  CSV_FILE_REQUIRED: 'CSV file is required.',
  DIAGNOSIS_SEARCH_SUCCESS: 'Diagnosis search successful',
  PARTIAL_ICD_CODE_REQUIRED: 'Partial ICDCode is required.',
  DIAGNOSIS_NOT_FOUND: 'Diagnosis is not found',
  INVALID_PARTIAL_ICD_CODE: 'Invalid partial ICDCode',
  INSURANCE_UPDATE_SUCCESS: 'Insurance information successfully updated',
  ALL_ORDER_DOCUMENTS_FETCHED: 'All order documents fetched successfully',
  MUST_BE_BOOLEAN: 'Field must be a boolean: ',
  PLEASE_SELECT_FILE: 'Please select at least one',
  SECONDARY_INSURANCE_DATES_REQUIRED:
    'Secondary insurance start and end dates are required when secondary insurance is true.',
  ORDER_DELETED_SUCCESSFULLY: 'Order deleted successfully',
  SUCCESS_STATUS: 'success',
  FAILED_STATUS: 'failed',
  INPROGRESS_STATUS: 'inprogress',
  PENDING_STATUS: 'pending',
  SALESFORCE_AUTHENTICATION_FAILURE_MESSAGE: 'Authentication Failure',
  FIRST_NAME_LAST_NAME_CONTAIN_ONLY_ALPHABETS:
    'First name and last name should contain only alphabets',
  ORDER_STATUS_MAPPING_NOT_FOUND: 'Order status mapping not found.',
  SALESFORCE_USER_NOT_FOUND: 'User not found.',
  SALESFORCE_USER_TOKEN_FAILED: 'Failed to generate Salesforce token.',
  FILE_DOWNLOAD_SUCCESS: 'File downloaded successfully.',
  HEALTH_PLAN_REQUIRED: 'Health plan is required.',
  ORDER_TYPE_ID_REQUIRED: 'Order Type ID is required',
  ORDER_TYPE_ID_NUMERIC_ERROR: 'Order Type ID must be a numeric value',
  CPT_CODE_SEARCH_SUCCESS: 'CPTCode search successful',
  CPT_CODE_NOT_FOUND: 'CPTCode not found',
  INVALID_PARTIAL_CPT_CODE: 'Invalid or missing partial CPTCode',
  COMPLETED: 'completed',
  DELETED: 'deleted',
  SUBMITTED: 'submitted',
  DRAFT: 'draft',
  RADIATION_ORDER_TYPE: 'Radiation',
  CHEMO_ORDER_TYPE: 'Chemo',
  OFFICE_VISIT_ORDER_TYPE: 'Office Visit',
  RADIATION_ORDER_TYPE_ID: 3,
  OFFICE_VISIT_ORDER_TYPE_ID: 2,
  USER_ROLE_HAS_BEEN_CHANGED: "The user's role has been changed.",
  SALESFORCE_RECORD_TYPE_ID: '0124T000000cZcbQAE',
  SALESFORCE_NEXT_CYCLE_NUMBER: 'x11 Cycle',
  SALESFORCE_CHEMO_AUTH_TYPE_C: 'Cycle 1',
};
